//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDataAssembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART_TABLE
    {
        public int ID { get; set; }
        public string USR_ID { get; set; }
        public string INV_ID { get; set; }
        public string COUNT { get; set; }
    }
}
