//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDataAssembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public string ID { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> INSTOCK { get; set; }
        public Nullable<int> RESERVED { get; set; }
    }
}
